### ISSUE TITLE
VFX Templating does not capture search types

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1426]
There seems to be missing all the custom stypes ... for VFX, this means the project has to be named vfx in order to capture the vfx search types ... that means a template project has to be named that which matches the namespace of the custom entities.

If I create a vfx2 and make it a plugins, the definition of the vfx search types do not get created.  Not sure if this is an known old problem, but is should understand somehow that the vfx search types are part of the new template.

**Comment by listyque** [comment]
insert.set_value('project_code', """vfx""")
Can be found in sthpw_pipeline.spt file.

**Comment by remkonoteboom** [comment]
It has to do with the Project Type.  The exported plugin had a project type of "simple" which means it couldn't find the vfx search types to export.  Setting this to vfx fixes the problem.
