### ISSUE TITLE
Sidebar blanks out when managing sidebar

### ISSUE THREAD

**Issue by CeltonMcGrath** [Southpaw-TACTIC/TACTIC#1432]
Issue: Sidebar appears blank after managing sidebar 
Steps to reproduce: Go to TACTIC Admin -> Project -> Manage sidebar. Change ordering or add/delete items, and press save. 

<img width="961" alt="sidebar_bug" src="https://user-images.githubusercontent.com/5935477/82457788-d9947580-9a83-11ea-8df6-f43d33d8f2e9.png">

**Comment by remkonoteboom** [comment]
Until this is fixed, work around it reload the page and it will reappear.

**Comment by remkonoteboom** [comment]
This was because the function:
spt.panel.refresh("side_bar")
no longer worked with the new BMD sidebar.  This is fixed in the associated pull request.
