### ISSUE TITLE
sType Table Manager Missing edit Combobox

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1434]
SearchTypeManagerWdg_DropdownMenu is missing, so there is no way of adding new stype or new table column in sType Table Manager

**Comment by remkonoteboom** [comment]
There were two Search Type Managers ... one from the Sidebar and the other from the Project Startup.  I think the latter was meant to replace the former, but it is missing the column definition manager.  I have added the column definition manager. 

Is there any reason to have the old search type manager.  As far as I can tell, this one completely replaces and can do far far more as well.

![search_type_manager jpb](https://user-images.githubusercontent.com/2145947/82741638-547abc00-9d22-11ea-8c8f-27d146708177.png)

The new column "Column Definition" will open up a pop that was the interface from the Search Type manager.

**Comment by listyque** [comment]
It looks like Manage sTypes is now pointless.

**Comment by remkonoteboom** [comment]
I will put the "newer" Search Type manager in the side bar for this issue.
