### ISSUE TITLE
Slow Saving Definition of Column and Schema

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1436]
When clicking save on column definition it is taking long time. About 10-15 seconds. Looks like js problems

**Comment by remkonoteboom** [comment]
I have seen this before in other areas.  This was due the temp folder (<TACTIC_TEMP_DIR>/temp) having had a huge number of command/widget key files created.   They would add up quickly (100,000s of files).  This slowed interaction considerably.

This bug has been fixed, but you may still have a LOT of temp files around that would cause this problem.  Please delete all of the files in the temp folder and see if this improves the speed.

**Comment by listyque** [comment]
I had about 1.64 gb of temp files with single json string each. Is there any real usage for that?
What happens if i use HDD instead of SSD? Server will blow up? :)

**Comment by remkonoteboom** [comment]
This was the result of a earlier bug.  That bug has been fixed and shouldn't produce such enormous number of files.  You can safely remove them.

**Comment by listyque** [comment]
Yes this is solved the problem. Thanks
