### ISSUE TITLE
Edit sthpw/search_object puts random color in color input

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1447]
**Describe the bug**
When you try to edit Search Objects table with Edit menu it puts any color in Edit Line input

**To Reproduce**
1. Go to sthpw/search_object table
2. Right click on any item > Edit
3. Look for Color
4. See random color (even if there is no color on item in db)

**Expected behavior**
Color which belongs to search type or blank if color not set

**Comment by remkonoteboom** [comment]
The color input has been switch to use the default browser chooser.   The one used before was wonky at best.
