### ISSUE TITLE
Duplicated "project_view" for SideBarWdg widget config

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1451]
**Describe the bug**
When i apply project plugin to empty project it is not replacing existing project_view config. Which cases issues when i gather config for different purposes.

**To Reproduce**
1. Create Empty project
2. Apply VFX project Plugin
3. Go to config/widget_config table
4. Search for SideBarWdg search_type column
5. See old "project_view" is not replaced

**Expected behavior**
Only one "project_view" in config.

**Comment by remkonoteboom** [comment]
What are the code values for these two entries?  In the VFX plugin, the code for "project_view" is "1VFX".  Technically, if the VFX plugin was reloaded, it would replace this.  However, I am assuming that the project view was created outside of the VFX plugin ... maybe on project creation and they have different codes. 

Right now, if the code on the widget_config table is unique, then loading in an entry with the same view and other data won't replace and you could have 2 project views.

The plugin manifest would have to treat the sidebar differently, which it doesn't do with the current plugin.

**Comment by remkonoteboom** [comment]
I think this is fixed in the associated pull request.  I tried on one of my projects with a pre-created project and it seemed to replace it.

**Comment by listyque** [comment]
The old one is "Example", which is created with empty_project by default. And has his own code
