### ISSUE TITLE
Preview File Checkin Bug

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1464]
**Describe the bug**
When i do checkin "icon" process with context menu (Change Preview Image) everything is as expected.
But If i create New SObject, and choose file as a preview with tactic.ui.widget.upload_wdg.SimpleUploadWdg it messes up with preview and icon files.
_icon file becomes big, and _preview is small

**To Reproduce**
1. Click on Create New SObject in form
2. Upload file to Preview chooser
3. Save new SObject
4. See error uploaded files are messed up

**Expected behavior**
Same behavior as in "Change Preview Image"

**Comment by remkonoteboom** [comment]
Those two are running two different codes, however, it's not completely clear at the moment why they are different.  They do produce different names for the files.  The Preview in the edit widget does add an extra _icon to it ... for example, these were my files with a test:

```
/spt/data/sites/vfx/assets/vfx2/asset/CHR003/icon/.versions/160713-F-HC633-968-640x360_icon_icon_v001.png
160713-F-HC633-968-640x360_icon_icon_v001.png
15.9 KB
/spt/data/sites/vfx/assets/vfx2/asset/CHR003/icon/.versions/160713-F-HC633-968-640x360_icon_v001.jpg
160713-F-HC633-968-640x360_icon_v001.jpg
40.1 KB
/spt/data/sites/vfx/assets/vfx2/asset/CHR003/icon/.versions/160713-F-HC633-968-640x360_web_icon_v001.jpg
160713-F-HC633-968-640x360_web_icon_v001.jpg
39.6 KB
```

Note that they do, however, produce the size appropriately (bear in mind, my test image is a tiny 40.1K, but the web version is 39.6K and the icon is 15.9K)

**Comment by listyque** [comment]
This is all right. But in one case:
Icon is JPG
in another Icon is PNG.

`Checking with creating SObject:

/home/apache/assets/testing/complex_testing_phase_four/props/Boy/work/icon/Boy_icon.jpg
Boy_icon.jpg
94.8 KB
/home/apache/assets/testing/complex_testing_phase_four/props/Boy/work/icon/Boy_icon_icon.jpg
Boy_icon_icon.jpg
100.9 KB
/home/apache/assets/testing/complex_testing_phase_four/props/Boy/work/icon/Boy_icon_web.png
Boy_icon_web.png
10.2 KB


Checkin as Change Preview Image:

/home/apache/assets/testing/complex_testing_phase_four/props/toDelete/work/icon/versions/mushroom.jpg
mushroom.jpg
75.1 KB
/home/apache/assets/testing/complex_testing_phase_four/props/toDelete/work/icon/versions/mushroom_icon.png
mushroom_icon.png
23.7 KB
/home/apache/assets/testing/complex_testing_phase_four/props/toDelete/work/icon/versions/mushroom_web.jpg
mushroom_web.jpg
75.1 KB`

**Comment by remkonoteboom** [comment]
Strange.  That is decidedly different from what mine is showing.  Somehow, in your case, as you mentioned in your original post, the png is the"web" file.  In mine, it is the "icon" file.  It might be that some part of the code is relying on a hash for order and messing up.

**Comment by listyque** [comment]
Can i provide some extra info for You?

**Comment by remkonoteboom** [comment]
Is this consistent no matter the filename?

**Comment by remkonoteboom** [comment]
Also, what are your naming conventions for this stype?  The one I am using does not have a naming convention set, so maybe this affects it.

**Comment by listyque** [comment]
File name can be anything.
Naming:
folder: {project.category}/{project.code}/{search_type.table_name}/{sobject.name}/work/{snapshot.process}
file: {sobject.name}_{snapshot.context}.{ext}

Snapshot:
```
<snapshot timestamp="Wed Jun  3 20:44:42 2020" context="icon" search_key="complex/props?project=complex_testing_phase_four&code=PROPS00033" login="admin" checkin_type="auto">
<file file_code="FILE00029182" name="Boy_icon_v001.jpg" type="main"/>
<file file_code="FILE00029183" name="Boy_icon_v001_icon.jpg" type="icon"/>
<file file_code="FILE00029184" name="Boy_icon_v001_web.png" type="web"/>
</snapshot>
```
Change Preview Snapshot:
```
<snapshot ref_snapshot_code="SNAPSHOT00006362">
  <file file_code="FILE00029188" name="Boy_icon.jpg" type="main"/>
  <file file_code="FILE00029189" name="Boy_icon_icon.jpg" type="icon"/>
  <file file_code="FILE00029190" name="Boy_icon_web.png" type="web"/>
</snapshot>

```

**Comment by remkonoteboom** [comment]
Ok, it has nothing to do with naming.  I can reproduce it.  I wan't looking at the snapshot definition and mine is the same as yours.

**Comment by remkonoteboom** [comment]
This is fixed in linked pull request.
