### ISSUE TITLE
Check-in History showing all possible snapshots

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1465]
**Describe the bug**
In the SObject info widget Checkin history tab showing all snapshots for every SObjects

**To Reproduce**
1. Click on preview of SObject
2. Go to Check-in History tab
3. Click Reload tab
4. See there some shapshots not related to particular SObject

**Expected behavior**
Only Related Snapshots

**Comment by remkonoteboom** [comment]
I am having trouble reproducing this.  Could you add this print statement in line 763 below in src/tactic/ui/tools/base_table_layout_wdg.py:

 ```
760             self.alter_search(search)
 761             self.items_found = search.get_count()
 762
 763             print("search: ", search.get_statement() )
 764
 765
 766             if self.do_search == True:
 767                 self.sobjects = search.get_sobjects()
```
When I do this for an asset in the VFX module, it prints out:

`search:  SELECT "sthpw"."public"."snapshot".* FROM "sthpw"."public"."snapshot" WHERE "snapshot"."search_type" = 'vfx/asset?project=vfx2' AND "snapshot"."search_code" = 'CHR001' AND ("snapshot"."s_status" != 'retired' or "snapshot"."s_status" is NULL) AND ("snapshot"."s_status" != 'retired' or "snapshot"."s_status" is NULL) LIMIT 100`

As you can see, it scopes out the search_code appropriately for "CHR001".  If yours is seeing more snapshots, this query would show why.

**Comment by listyque** [comment]
Something must be went wrong on my side. After updating to latest ver this cannot be reproduced

**Comment by remkonoteboom** [comment]
No problem.  Will mark this invalid and if it comes up again, we can open another issue (or reopen this one) and investigate.
