### ISSUE TITLE
get_preallocated_path is returning 'Value for [file_name] is None'

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1468]
**Describe the bug**
Api and also FileCheckin class returning None when trying to get file name with method "get_file_name"

**To Reproduce**
1. Run serverside or remote api script:
get_preallocated_path('SNAPSHOT00006367')
2. See error

**Expected behavior**
Something like "/home/apache/assets/dolly3d/episodes/Ep98/versions/SHOT00304"

**Comment by listyque** [comment]
I am making so much bugreports because i am in preparation to switch from 4.5 > 4.8.

**Comment by remkonoteboom** [comment]
Not a problem.

I looked into this a little bit.  There was a stack trace that was happening, which I can stop, however, there are a number of dependent conditions here.  I assume your snapshot exists in the database already?  Does it have file entries added already or is it an empty snapshot?

**Comment by listyque** [comment]
No matter if this is already existing snapshot, or not commited yet. Results are the same
