### ISSUE TITLE
Update versionless gets called twice on check-in

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1470]
**Describe the bug**
Update versionless is getting called twice during the check-in process (one each for current and latest).  Should investigate whether this is really necessary (probably not).

**To Reproduce**
1. Check-in a file in debug mode
2. Trace Snapshot.update_versionless (which will be called twice for each mode)

**Expected behavior**
Should be optimized to be only called once.

**Comment by listyque** [comment]
There is also similar bug when deleting Snapshot.
Versionless creation called and it creates empty versionless.
Should i do one more issue?

**Comment by remkonoteboom** [comment]
Yes, track it separately on an new issue.  I prefer smaller discrete issues so that they don't stay open forever.

**Comment by remkonoteboom** [comment]
I have optimized the check-in process.  It is all in the link pull request.  It's quite a bit of changes, but mostly it's removing all the extra commit statements.  I have added a new "ingest_mode", however, that should be considered beta as I am still testing it.  Normal check-in should be faster (a little less than twice as fast).   On test check-ins, I was getting about 100ms per check-in.  A good chunk of this is finding the md5 checksum of this file

At any rate, versionless is now only called once per check-in.

**Comment by listyque** [comment]
Can md5 be disabled in project settings?
I see only use for this is to check file after download. But in my opinion all download processes have self-checking packets, and double check is not required to be sure file is downloaded properly.

**Comment by listyque** [comment]
> Yes, track it separately on an new issue. I prefer smaller discrete issues so that they don't stay open forever.

That was on 4.5, i did not found same issues on 4.8 yet.

**Comment by remkonoteboom** [comment]
The MD5 signature was used in some places to detect if there were changes in the file.  This would allow an interface to quickly check if the file you are about to check in had any changes from the last version and indicate that there was a different.  An MD5 is ideal for this.

That being said, it could be made option.  I will create a new issue for this as it is separate from this one.

**Comment by listyque** [comment]
> The MD5 signature was used in some places to detect if there were changes in the file. This would allow an interface to quickly check if the file you are about to check in had any changes from the last version and indicate that there was a different. An MD5 is ideal for this.
> 
> That being said, it could be made option. I will create a new issue for this as it is separate from this one.

As an option md5 process could be scheduled as a separate process, non-blocking actual check-in
