### ISSUE TITLE
Icon generator does not fully respect naming.

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1473]
**Describe the bug**
When i checkin my mp4 files, tactic tries to generate preview and icon files. Unfortunately it does not fully respect all naming rules. For example, i have my previews and icons in different folders, but icon generator creates files in the same folder with mp4. And also strange results with the vesionless.
Something similar happening when tactic tries to generate versionless for jpg's.
versionsnaphsot:
```
<snapshot timestamp="Sat Jun  6 20:39:46 2020" context="animation" search_key="tvs/episode?project=aquariki&code=EPISODE00003" login="admin" checkin_type="strict">
  <file file_code="FILE00030018" name="Episode Pilot_animation_v001.mp4" type="main"/>
  <file file_code="FILE00030020" name="Episode Pilot_animation_v001_web.jpg" type="web" use_naming="false"/>
  <file file_code="FILE00030021" name="Episode Pilot_animation_v001_icon.png" type="icon" use_naming="false"/>
</snapshot>
```
Versionless snapshot (note, there is duplicated icons and web):
```
<snapshot ref_snapshot_code="SNAPSHOT00006477" timestamp="Sat Jun  6 20:39:47 2020" context="animation" search_key="tvs/episode?project=aquariki&code=EPISODE00003" login="admin" checkin_type="strict">
  <file file_code="FILE00030022" name="Episode Pilot_animation.mp4" type="main"/>
  <file file_code="FILE00030023" name="Episode Pilot_animation_web.jpg" type="web"/>
  <file file_code="FILE00030024" name="Episode Pilot_animation_icon.png" type="icon"/>
  <file file_code="FILE00030025" name="Episode Pilot_animation_web.jpg" type="web" use_naming="false"/>
  <file file_code="FILE00030026" name="Episode Pilot_animation_icon.png" type="icon" use_naming="false"/>
</snapshot>
```

**To Reproduce**
Naming for folders:
{project.code}/episodes/{sobject.name}/renders{@CASE( @GET(file.type) == 'playblast', '/'+'__preview', @GET(file.type) == 'web',  '/'+'__preview/web', @GET(file.type) == 'icon', '/'+'__preview/icon')

1. Checkin any avi or mp4
2. Wait until previews generated
3. Look for the files results

**Expected behavior**
Files generated should respect naming expressions.

**Comment by remkonoteboom** [comment]
Are you using ffmpeg to generate these previews?

**Comment by listyque** [comment]
How can i check which module TACTIC uses to generate previews?

**Comment by listyque** [comment]
When i got some free time i will try to fix this and make a PR.
Looks like i am the only one who care so much about file naming :D

**Comment by remkonoteboom** [comment]
Does this pull request:

https://github.com/Southpaw-TACTIC/TACTIC/pull/1498

fix this issue?

**Comment by listyque** [comment]
This PR fixes bad paths for previews in tiled layout widget.
But i am in the process of creating a fix for icon generator
