### ISSUE TITLE
"Cannot read property '0' of undefined" when saving projects security 

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1476]
**Describe the bug**
tactic.ui.common.SimpleTableElementWdg checkbox isn't visually working, but seems to be changing its state. 
When i try to save Projects Security i got message "Cannot read property '0' of undefined"

**To Reproduce**
1. Go to Projects security
2. Click on any item checkbox
3. Click save

**Comment by remkonoteboom** [comment]
This is very strange. Project security and sType Security exhibits this behavior, but Link Security, Process Security and  Gear  Menu Security do not, even though they are all using the same widget class.

**Comment by remkonoteboom** [comment]
So, the preview had a old style behavior that somehow interfered with the event on the checkbox.  This is fixed in attached pull request.

As well, the saving issue has been fixed.
