### ISSUE TITLE
Display Definition for Simple edit mode in Manage Sidebar missing

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1480]
**Describe the bug**
When trying to edit sidebar in Simple mode, all of the available options is missing.

**To Reproduce**
1. Go to Sidebar Edit mode
2. Select any link item
3. Go to Simple Edit Mode
4. See there is no options

**Expected behavior**
All Available options will displayed

**Comment by remkonoteboom** [comment]
This has been fixed in the linked pull request.
