### ISSUE TITLE
method "ERRORMETHOD" is not supported 

### ISSUE THREAD

**Issue by CeltonMcGrath** [Southpaw-TACTIC/TACTIC#1482]
**Describe the bug**
While running my server from startup_dev, I am constantly getting this error through spt.alert:

_method "ERRORMETHOD" is not supported_

In the dev output, two lines appear to be associated;

_ERROR:  no element found: line 1, column 0
b''_

**To Reproduce**
1. Any action that calls the API can cause this error. Calling the same action again does not cause the error and the request succeeds.

**Expected behavior**
No errors

**Comment by remkonoteboom** [comment]
We had a discussion on this:
http://forum.southpawtech.com/showthread.php?tid=68&highlight=errormethod

This seems to be an underlying Python or one of the Python modules bug.  Doing a "dnf update" resolved the issue, at least for me on Fedora 31.

**Comment by CeltonMcGrath** [comment]
Great thanks! 

Just updated, you can close and I'll add to that discussion if I have any more errors.
