### ISSUE TITLE
DiscussionWdg should refresh or provide user feedback after adding a note. (REOPEN)

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1484]
**Describe the bug**
Bug is the same as described in: https://github.com/Southpaw-TACTIC/TACTIC/issues/1450 

**To Reproduce**
1. Go to tasks table
2. Enable groupping of any king
3. Try to add any note in a table
4. See nothing is updates after not is added

**Expected behavior**
Notes dialog closed, and user gets feedback, on note widget or on table. Or both.

**Comment by remkonoteboom** [comment]
Should be fixed now in linked pull request.
