### ISSUE TITLE
New style workflow > json issues.

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1491]
**Describe the bug**
I am forcing some issues and other strange things when trying to do backport of old 4.5 style workflow things to 4.8.
So there will be some more issues i will find in the future.
The first:
Earlier all optins of the workflow node was stored in the xml format, new style is json, but not all old widgets uses new style.
For example, when i go to Configuration and add tasks pipeline from there it goes to old xml place. Then when i go to worflow editor and Right click> edit tasks pipeline i got message about creating new pipeline. So tactic widgets do not see any pipelines for tasks i created. Like task insertion widget "tactic.ui.widget.misc_input_wdg.TaskStatusSelectWdg".

Same things with the color and Label, and the "tactic.ui.table.TaskElementWdg", this widget searching for the xml values, which is now saved in json format.

I will be adding some more related to this issues when i face them.

**Comment by remkonoteboom** [comment]
There is a pull request from Diego that is dealing with some of these issues with Task Pipeline not respecting new style workflow json format:

https://github.com/Southpaw-TACTIC/TACTIC/pull/1444

I really haven't had a change to look at it and validate that everything was working.

**Comment by remkonoteboom** [comment]
I have merged Diegos pull request which I have test and it seems to work.  I did notice another minor issue which is harmless, but I will record in a separate issue.
