### ISSUE TITLE
Selecting check-boxes does not work in Hidden Row Wdg

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1495]
**Describe the bug**
Single or multiple selection with checkboxes visually not working

**To Reproduce**
1. Go to any table with hidden row
2. Open Hidden row widget
3. Select items with checkbox
4. See it unchecked back

**Expected behavior**
Selection work as expected

**Comment by remkonoteboom** [comment]
Is this just in the hidden columns or all of the table columns.   I see this huge checkbox on all of the checkboxes.

**Comment by listyque** [comment]
This is how it looks:
![avNCOfOq3K](https://user-images.githubusercontent.com/13370598/85585502-bc396500-b648-11ea-9ea3-70c623d779f1.gif)

**Comment by remkonoteboom** [comment]
Ok, yes, I see the same behavior.  I looked into it a bit and it is not at all apparent why this is so.  For the most part both those using identical code.  It looks like there is some extra event on embedded tables that is "double clicking" this checkbox.
