### ISSUE TITLE
Admin mode always with light theme

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1499]
**Describe the bug**
Something wrong with the admin mode. Also with the custom-links for projects

**To Reproduce**
1. Go to admin mode
2. See theme is light

**Comment by remkonoteboom** [comment]
What do you mean by "admin mode" ... do you mean with the URL ending with "/admin"?

**Comment by listyque** [comment]
Yes!
http://HOST/tactic/project/admin/link/

**Comment by remkonoteboom** [comment]
Sorry ... didn't read the title ... ignore my last comment.  I think the admin site has been a light mode for a long while, which is the default mode.  The vfx project is only dark because of a project setting.

**Comment by listyque** [comment]
Ok, but i set dark mode in projects settings. And it worked in 4.5. Also the same light theme appears in custom URLs...

**Comment by remkonoteboom** [comment]
I'll take a look at what's going on.  Maybe we need a separate setting for the admin site ... right now it's hard coded for the admin site only.

**Comment by remkonoteboom** [comment]
For now, I have added a project setting "palette/admin" which can set the admin site palette.  See if this works before.  Maybe we need to have this as a global setting in the config?

**Comment by listyque** [comment]
I should go to admin site and add palette/admin proj_settings? This should be enough in my opinion

**Comment by remkonoteboom** [comment]
Yes, that should work.
