### ISSUE TITLE
Notes widget lies under other UI

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1500]
**Describe the bug**
When you try to see notes in hiddenRow widget notes widget lies under the UI

**To Reproduce**
Attached in video:
![XYHfKxijUu](https://user-images.githubusercontent.com/13370598/85954191-5cabc400-b97e-11ea-921a-a95b0cbbe5b7.gif)

**Comment by remkonoteboom** [comment]
This pull request has a commit which tries to fix this.  It seems to work but the big difference is that if you change tabs, the notes does not disappear anymore.  I am not sure if this is a desirable feature.  Maybe the click-off close should be disabled for notes?

**Comment by listyque** [comment]
May be the lost focus notes widget should closed automatically? Like when i click to other notes and i see notes widgets stack on each other.
Lost focus = close widget.
What You think?

**Comment by remkonoteboom** [comment]
The notes widget currently has a click off behavior: ie: if you click outside of the note widget, it will disappear (however, in a few cases, this does not completely work, such as when you open up another notes widget that has notes or when you switch tabs).  Other than that, the behavior of the notes seems to work as expected.  If this behavior doesn't work well, we can always open up a new issue as this one is solved by the current pull request.

**Comment by listyque** [comment]
Ok. This i checked this fix. It is sure fixed, but notes widget is not working now when it called from collapsable widget...
