### ISSUE TITLE
Ingesting into Art Reference in the VFX template gives error

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1515]
**Describe the bug**
When ingesting a bunch of images into art reference, several warnings are seen in the output.

`WARNING: relationship [general] not supported`

This results in a final error:

```
method:  finish ({'ticket': 'PORTAL-vfx-4591fa673694b09253e', 'site': 'vfx', 'project': 'vfx', 'palette': 'dark', 'api_key': '', 'language': 'javascript'}, {})
WARNING: relationship [general] not supported
Error with query (Error):  sthpw INSERT INTO "sthpw"."public"."sobject_log" ("action", "login", "timestamp", "transaction_log_id") VALUES ('insert', 'admin', now(), '513')
Exception:  null value in column "search_type" violates not-null constraint
DETAIL:  Failing row contains (1078, null, null, null, null, admin, 2020-07-16 12:25:33.180836, 513, null, null, null, insert).
```

This is specific to the "Art Reference" object because it has a general relationship defined.

**To Reproduce**
1. Go to Art Reference
2. In the gear, select File -> Ingest Files
3. Add a bunch of images in the ingest UI
4. Click "Upload Files"

**Expected behavior**
An entry per file is created

**Comment by listyque** [comment]
It was fixed by deleting general relationship from vfx plugin?

**Comment by remkonoteboom** [comment]
I will try that ... this was in the plugins.  I still been updating the plugins and haven't moved the template to use those plugins yet.

**Comment by remkonoteboom** [comment]
It is fixed by deleting the general relationship.  Since moving the template is handled in another issue, I will close this one as the VFX plugin has been fixed.
