### ISSUE TITLE
Support xmlrpc python api to work through proxy.

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1519]
Is your feature request related to a problem? Please describe.**
Sometimes user only have access to internet through proxy. I had to do manually fixes to client api.
For example add proxy wrapper class to xmlrpclib.Transport
```server.set_transport(proxy_transport)```

in a tactic_server_stub it would be:
```
        if self.transport:
            self.server = xmlrpclib.Server(url, allow_none=True, transport=self.transport)
        else:
            self.server = xmlrpclib.Server(url, allow_none=True)

```
It worked for me for long time, but i never did any PR. Should i?

**Comment by remkonoteboom** [comment]
Yes, please.

**Comment by listyque** [comment]
I made a PR #1525
