### ISSUE TITLE
DeleteCmd does not delete versionless symlink

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1522]
**Describe the bug**
When file deleted from the Web Ui or api symlink versionless files still remain in the repo folders

**To Reproduce**
1. Checkin any file with versionless in symlink versionless mode
2. Delete snasphot with those files
3. Go to your repo folder to see there is symlink file still exists

**Expected behavior**
All files are cleared up completely

**Comment by remkonoteboom** [comment]
Linked pull request should fix the issue.
