### ISSUE TITLE
Custom URL's Layouts does not respect theme color

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1531]
**Describe the bug**
When i create custom URL with some Layout, even if Dark theme is set everywhere i got white theme.

**To Reproduce**
1. Create some custom Tiled Layout
2. Create Custom URL link to it
3. Open this link
4. See there is white

**Expected behavior**
Same theme accent as in the project

**Screenshots**
![image](https://user-images.githubusercontent.com/13370598/88429461-5edb3400-cdff-11ea-82f4-d0b61cdf01de.png)

**Comment by remkonoteboom** [comment]
I believe that the fix for the Project List dark theme also fixes this issue.
