### ISSUE TITLE
Some UI minor bugs/strange behaviors

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1532]
Strange things with a simple search widget. When Table firs opened it has title:
![image](https://user-images.githubusercontent.com/13370598/88429921-3142ba80-ce00-11ea-916a-8ac95ec81efe.png)
Then, after refresh button near search widget clicked it disappears:
![image](https://user-images.githubusercontent.com/13370598/88429975-559e9700-ce00-11ea-90d1-22fd32ba5388.png)

-----------

Also, comparing to previous <4.8 releases of tactic Save button was always on the left side, and it was actually more comfortable to find it and click faster.
Old one:
![image](https://user-images.githubusercontent.com/13370598/88430157-a31b0400-ce00-11ea-97ff-f4b60cf71940.png)
The new:
![image](https://user-images.githubusercontent.com/13370598/88430188-ac0bd580-ce00-11ea-9ffd-0793947a4e11.png)
Same with add and cog buttons.

------------

Styles bugs in search widget:
![image](https://user-images.githubusercontent.com/13370598/88430540-49ffa000-ce01-11ea-8d00-d1691efd8613.png)
![image](https://user-images.githubusercontent.com/13370598/88430550-4ff58100-ce01-11ea-8c4b-b0a9dda64664.png)

------------

Waving UI's texts
![image](https://user-images.githubusercontent.com/13370598/88430675-86330080-ce01-11ea-98c9-598d0c417377.png)
![image](https://user-images.githubusercontent.com/13370598/88430761-a9f64680-ce01-11ea-8a42-b0b8902c8feb.png)
Not working button with triangle below Cog button:
![image](https://user-images.githubusercontent.com/13370598/88430842-c8f4d880-ce01-11ea-8705-a7bc5095be0c.png)
Triggers for script editor is inactive:
![image](https://user-images.githubusercontent.com/13370598/88430916-f2adff80-ce01-11ea-89bc-d08c32e5a783.png)
Color theme glithes:
![image](https://user-images.githubusercontent.com/13370598/88430935-fe99c180-ce01-11ea-8b80-0f227c72bb2c.png)
![image](https://user-images.githubusercontent.com/13370598/88431080-4b7d9800-ce02-11ea-9e1a-7def5797c7d1.png)

**Comment by remkonoteboom** [comment]
Almost all of this is fixed.  I have created separate issues for ones that are not complete.
