### ISSUE TITLE
Log-on screen has UI overlaps

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1533]
**Expected behavior**
Color consistency with selected theme. Text hints not overlapped by lineedtis

**Screenshots**
![image](https://user-images.githubusercontent.com/13370598/88454744-49572000-ce7a-11ea-8086-e7850a3292ae.png)

**Comment by remkonoteboom** [comment]
I am not able to reproduce this.  This is what mine looks like on the latest 4.8.

![tactic_login](https://user-images.githubusercontent.com/2145947/88675863-69285700-d0b9-11ea-9f01-b977473db189.png)
