### ISSUE TITLE
Modern, with mobile support Gallery Widget

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1544]
**Is your feature request related to a problem? Please describe.**
Current implementation of Galley Widget is a little slower, and looks old, with jagged animation and preloading images in bg (for gallery with 100+ pics is a problem). Also it does not work on mobile devices as expected.

**Describe the solution you'd like**
Fixes to current implementation

**Describe alternatives you've considered**
Some open source js preview gallery

**Comment by remkonoteboom** [comment]
I think the best approach would be to put in an open source gallery in its place.  A cursory look shows there are a good number of them them that are superior to what is now in TACTIC.

**Comment by listyque** [comment]
Do You have any good candidate for that?

**Comment by remkonoteboom** [comment]
No.  I just took a quick look and quickly determined that it is pointless to create a custom one from scratch.  I would like to get one that is not too fancy and is well supported.  It would be a bonus if it could play video and view pdfs (using pdf.js)

**Comment by listyque** [comment]
This looks really promising: [https://github.com/sachinchoolur/lightgallery.js/](url)
