### ISSUE TITLE
Side Bar ignores "open" state

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1546]
**Describe the bug**
Rollout-menus of the sidebar ignoring their states from definition:

This should be displayed as opened:

```
<element name="my_dashboard" title="My Dashboard" icon="" state="open" is_visible="on">
  <display class="SideBarSectionLinkWdg">
    <view>my_dashboard</view>
  </display>
</element>

```
**To Reproduce**
1. Go to edit sidebar
2. Add new "Folder"
3. Set it's state as "open"
4. Refresh sidebar and see it is still closed

**Expected behavior**
Opened Rollout-items if theirs state is "open"

**Comment by listyque** [comment]
Any possible thoughts how to fix this?

**Comment by diegocortassa** [comment]
I guess this was left out when tactic was converted to bootstrap, I made PR #1659 to fix it

**Comment by listyque** [comment]
Looks great, thanks!

**Comment by diegocortassa** [comment]
@listyque I guess we can close this issue?

**Comment by listyque** [comment]
Yes, fixed.
