### ISSUE TITLE
Issue with title disappearing in top of Table Layout

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1548]
**Describe the bug**
Refer to this bug (which contains many issues)
https://github.com/Southpaw-TACTIC/TACTIC/issues/1532

**To Reproduce**
1. Strange things with a simple search widget. When Table first opens, it has title
2. Then, after refresh button near search widget clicked it disappears:

**Comment by diegocortassa** [comment]
This bug should be fixed by PR #1645
