### ISSUE TITLE
On Table Layout, clearing the keywords does not actually clear it

### ISSUE THREAD

**Issue by remkonoteboom** [Southpaw-TACTIC/TACTIC#1549]
**Describe the bug**
On the shelf of the table layout, there is usually a place to search quickly with keywords.  Adding a keyword works in the search, but if you try to clear it an press search, the keyword stays there.

**To Reproduce**
1. Go to any table.
2. Add a keyword to search
3. Clear the keyword input
4. Search again and you will see the keyword reappear

**Expected behavior**
Keyword should be cleared. 

**Workaround**
Refresh the entire view and it will disappear.

**Comment by listyque** [comment]
Could You check if the custom_filter for simple search is working also?

**Comment by diegocortassa** [comment]
I think this bug is related to issue #1623 and was solved in pr #1624 as well

**Comment by remkonoteboom** [comment]
This is an old issue and was fixed a while ago.
