### ISSUE TITLE
Chunk size for upload check-in affecting speed a lot

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1557]
**Describe the bug**
When Uploading files to server through http via python api there is a issue with bandwidth speed.
If chunk size set to 4 mb - the speed is about 60mbit/s, when chunk size is decreased speed of upload fall a lot to 5mbit/s.
I have 1 gbit ethernet connect to server and expect it to be near that speed. If i incrase chunk sizes to 64mb speed is increased a lot.

**To Reproduce**
1. Set chunk size for upload to 1mb
2. See the progress of Upload is slow

**Comment by listyque** [comment]
Uploading 1gb file
Upload time:  61.267704248428345  chunk size 16 mb
Upload time:  48.006547927856445 chunk size 64 mb
Upload time:  42.34089136123657  chunk size 256 mb

**Comment by remkonoteboom** [comment]
What the chunk size is doing is opening up a separate request and multi-part upload for each chunk and it will do so sequentially.  It is not terribly sophisticated but the overhead will be that a 16mb chunk will open up 16 time as many upload as many connections.  It will then take the each upload and append to the existing file on the server end.  This overhead is what is slowing down the file for smaller chunk sizes.  Maybe the chunk sizes should be somehow (automatically?) set depending on the size of the file (with a minimum of say 10Mb or so)

**Comment by listyque** [comment]
>Maybe the chunk sizes should be somehow (automatically?) set depending on the size of the file (with a minimum of say 10Mb or so)

Yes, i actually think about the same solution.
It should be smart enough to split big files to big chunks.

The second solution might be uploading more than one chunk at a time, leave them in a separate files and then merge in one file.
