### ISSUE TITLE
Keywords search ignores simple_filter view

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1561]
**Describe the bug**
When i try to cusomize keywords search with simple_filter i got nothing, it still uses the keywords search.
And also it affects search per columns (lacks search icon near column by the way):
![image](https://user-images.githubusercontent.com/13370598/91102486-ebcd1380-e671-11ea-834e-10e9d552c2ba.png)

**To Reproduce**
1. Add simple_search view for table definition <simple_search_view>simple_filter</simple_search_view>
2. Setup simple_filter to use name|description|keywords
3. See simple search still uses keywords only

**Comment by listyque** [comment]
It working in "hidden" mode:
![image](https://user-images.githubusercontent.com/13370598/92241781-79590080-eec7-11ea-845f-8e1d9baa3e7a.png)


But it is important to work with default mode

**Comment by remkonoteboom** [comment]
When you say "default" mode, what mode is that?  I think by default, the simple search is hidden.  Do you mean when the simple search is inline?

**Comment by listyque** [comment]
By default i mean "keyword" mode, which is supported multiple columns search in versions prior to 4.8.
By adding simple_filter view: <simple_search_view>simple_filter</simple_search_view>

**Comment by diegocortassa** [comment]
This is strange it works on my side, my link is:
```
    <element name="assets" icon="PHOTOS" title="Assets" state="" is_visible="on">
      <display class="LinkWdg">
        <widget_key>view_panel</widget_key>
        <layout>default</layout>
        <search_view>link_search:assets</search_view>
        <simple_search_view>asset_custom_filter</simple_search_view>
        <search_type>mfe/asset</search_type>
        <view>assets</view>
      </display>
    </element>
```

and asset_custom_filter is:
```
<config>
  <asset_custom_filter>
  <show_title>false</show_title>
    <element name='keywords'>
        <display class='tactic.ui.filter.KeywordFilterElementWdg'>
            <mode>keyword</mode>
            <column>name|description</column>
         </display>
    </element>
  </asset_custom_filter>
</config>
```

![Screenshot from 2020-09-15 12-16-33](https://user-images.githubusercontent.com/1223285/93198501-68bd4b80-f74d-11ea-8b6a-2f81bdbb0c5b.png)

**Comment by listyque** [comment]
Ok, when i explicitly pass ```<display class='tactic.ui.filter.KeywordFilterElementWdg'> and <element name='**keywords**'>``` it actually works.
What about per column search in table? Does it match tables?

**Comment by diegocortassa** [comment]
Sorry @listyque I don't understand your question, can you make an example with xml?

**Comment by listyque** [comment]
I am talking about filter buttons on columns:
![image](https://user-images.githubusercontent.com/13370598/93205863-2c93e600-f761-11ea-982a-82c25c93e2b6.png)
(it lack icon and invisible)

**Comment by listyque** [comment]
Add this to your asset_custom_filter:

```
    <element name='name'> 
        <display class='tactic.ui.filter.TextFilterElementWdg'> 
          <column>name</column> 
        </display> 
    </element>
```

**Comment by listyque** [comment]
Can be closed, because it is working, slightly different than in 4.5. In 4.8 simple search added per column search, which breaks backwards compatibility with 4.5 configs
