### ISSUE TITLE
DropElementWdg does not work with multiselect

### ISSUE THREAD

**Issue by diegocortassa** [Southpaw-TACTIC/TACTIC#1563]
**Describe the bug**
DropElementWdg does not work with multi select, when multiple parent are selected and a new child is dropped the already assigned children of all but the last parent are removed.

**To Reproduce**
1. Go to a many-to-many "planner" view, for example  'Global -> Users in Groups'
2. Select multiple groups
3. Drop a user on one of the selected group'
4. Only after the first save an alert "Only search types [sthpw/login] are accepted" appears, dismiss the alert
5. Click save
6. All but the last group will have only the new user, old user will be removed.

**Expected behavior**
The new item should be added to all the parent items but the already added children should be kept.

**Comment by diegocortassa** [comment]
@remkonoteboom @listyque can you reproduce this bug?

**Comment by listyque** [comment]
Yes. But also if groups was empty i can't even save. Getting message: "No changes have been made"

**Comment by diegocortassa** [comment]
I think I found the problem:

 the funcion `spt.drop.clone_src_to_droppable()` in `drop_element_wdg.py` is called for each selected row/drop_element to make it receive the dropped item

`spt.drop.clone_src_to_droppable()` calls `spt.table.accept_edit()` in `table_layout_wdg.py` to add the edited value to `spt_input_value` attribute for the save action

`spt.table.accept_edit()` cycles on each selected row again overwriting the `spt_input_value` on each row, this is the correct behaviour for "normal" multline edits because it copies the edited data to all selected rows

the result is that all `spt_input_value` attributes are overwritten when `spt.table.accept_edit()` is called by  `spt.drop.clone_src_to_droppable()` for the last row effectively copying the last drop contents to all the previous rows

I'm testing a solution if everything works well I'll submit a PR tomorrow!

**Comment by diegocortassa** [comment]
Turns out the fix was much simpler than finding the bug.
Just made PR #1568 which fixes this bug and a related problem when deleting a dropped element empties all other selected rows

**Comment by listyque** [comment]
Diego, do you know how to attach selected items without dragging them. Say, if i want custom button on table, and click on button would add selected items to drop element wdg?

**Comment by diegocortassa** [comment]
I guess you could use a JS function attached to a button inserted in the src row and add the row sObject to selected rows in the dst table.
Check "sobject_drop_action" in src/tactic/ui/table/drop_element_wdg.py
I think you have to get src_el and dst_el and call add_src_to_dst.
src_el should be easy because should be your button parent
for dst elements you ave to select the correct dom object.
