### ISSUE TITLE
TaskElementWdg style issues

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1564]
**Describe the bug**
Background color of combo boxes is pure white, so text unreadable:
![image](https://user-images.githubusercontent.com/13370598/91708584-337bff80-eb8a-11ea-99d7-c2531e520c3b.png)

Same with the users selection:
![image](https://user-images.githubusercontent.com/13370598/91708632-4262b200-eb8a-11ea-9c22-ad4eb99e93ab.png)

Also, users combo do not respect font size option

**Comment by remkonoteboom** [comment]
Chrome for some reason is treating transparent as white even though body background is dark color.  Not sure why.  Associated pull request fixes it.

**Comment by listyque** [comment]
Unfortunately it won't fixes this issue. What if we can add style to option items?

`<option style="background: color;"> `

**Comment by diegocortassa** [comment]
I see the same problem. For now I commented line 2481 in src/tactic/ui/table/task_element_wdg.py the assignee in TaskElementWdg becomes dark, not beautiful but i couldn't find any better workaround
