### ISSUE TITLE
Browser freezes when clicking on refresh near simple search

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1565]
**Describe the bug**
On Chrome browser when clicking on refresh button i got a lot of messages in log:
![image](https://user-images.githubusercontent.com/13370598/92243264-e40b3b80-eec9-11ea-878e-430748326dcf.png)
The browser is freezes

**To Reproduce**
1. Open browser console
2. Click on refresh 
![image](https://user-images.githubusercontent.com/13370598/92243306-f5544800-eec9-11ea-9763-24e4884183ea.png)

3. See a lto of messages in logs and browser freezing

**Comment by remkonoteboom** [comment]
Is the freezing behavior and the warnings related?  Looking at the warnings, this appears to be a jQuery issue:

https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive

I don't see the freezing on Chrome at any rate, but I do see the warnings.

**Comment by listyque** [comment]
I got freezing not all the time. But users do get this more often

**Comment by remkonoteboom** [comment]
The search request is done asynchronously, however, if it is a big table and depending on the elements in that table, is it possible there is a large of amount of javascript being run?  This would cause the browser to appear to freeze.  If you look at the performance tab on the Chrome dev tools, this will show that this is an issue.  It is possible that a lot of redundant or non-optimized javascript is being run and is really noticed on large tables (with lots of columns or rows)

**Comment by listyque** [comment]
I think it's can be closed, as it can't be reproduced anymore
