### ISSUE TITLE
Checkin through client API throws error ('str' object has no attribute 'decode')

### ISSUE THREAD

**Issue by DittoLabsNg** [Southpaw-TACTIC/TACTIC#1591]
**My aim**
I'm not sure if this is a professional way to handle this but, I created a Django app as an API endpoint to communicate with Tactic from Toon Boom Harmony.

**Methodology**
I copied the client directory from the Tactic source code and put it in my Django src directory(I also added the **tactic_client_lib** path to the **sys.path**). By doing this I can query the Tactic app from my Django views(get, post data and also do some logic).
My first test was the login to the Tactic app which worked(I could return the auth ticket)

**The  Error**
My second test was the file checkin using the **simple_checkin()** method. I added all the required arguments including the **file_path** which is a string of the file location but, each time I run the checkin it throws an error ('str' object has no attribute 'decode').
When I did my findings I noticed that in the **simple_checkin()** method, one of the first major action is the **upload_file()** method [if there is arg mode="upload" on **simple_checkin()**]. This **upload_file()** method uses the **UploadMultipart** class. 
Now, there is a line in this class that gets the filename from the file path and tries to decode it with args UTF-8, like this -
 
`basename = basename.decode(sys.stdout.encoding)` the basename was declared from `basename = os.path.basename(path)` which is the original filename from the **file_path**. Also the `sys.stdout.encoding` prints UTF-8 in the python shell.

The `basename = basename.decode(sys.stdout.encoding)` is the line that throws this error. Now my question is, what exactly am I doing something wrong here?

**Comment by lwinmoe** [comment]
This Python 2 vs 3 issue has been fixed in 4.8. Please consider upgrading to 4.8. Otherwise, try this:

```
                 try:
                    if getattr(sys.stdout, "encoding", None) is not None and sys.stdout.encoding:
                        basename = basename.decode(sys.stdout.encoding)
                    else:
                        import locale
                        basename = basename.decode(locale.getpreferredencoding())
                except AttributeError:
                    # Python3 has no decode method on strings objects
                    pass


```
