### ISSUE TITLE
how can i delete stype?

### ISSUE THREAD

**Issue by aixzhou0216** [Southpaw-TACTIC/TACTIC#1625]
VM tactic 4.8
Is there a way to delete stype?
thanks

**Comment by remkonoteboom** [comment]
Yes, there is, but be careful as it could potentially delete a lot of data.  Search types are also not often in isolation as there could be other search types dependent on it.  I am assuming you just create this search type and want to clean it up, which is the best reason to delete a search type.

Deleting a search type can be done in the Schema Manager.

From the configuration tab, click on the Setup button and then select the Create Schema swatch.
Or alternatively, press the "2" button which will bring up a window and click "Project Schema".

This will open up the schema editor.  Right click the node of the search type that you wish to delete and select "Delete sType".  A popup will open up showing you dependencies you also wish to remove (notes, tasks, snapshots, etc). 

Click "Delete" to delete.

**Comment by aixzhou0216** [comment]
> Yes, there is, but be careful as it could potentially delete a lot of data. Search types are also not often in isolation as there could be other search types dependent on it. I am assuming you just create this search type and want to clean it up, which is the best reason to delete a search type.
> 
> Deleting a search type can be done in the Schema Manager.
> 
> From the configuration tab, click on the Setup button and then select the Create Schema swatch.
> Or alternatively, press the "2" button which will bring up a window and click "Project Schema".
> 
> This will open up the schema editor. Right click the node of the search type that you wish to delete and select "Delete sType". A popup will open up showing you dependencies you also wish to remove (notes, tasks, snapshots, etc).
> 
> Click "Delete" to delete.

I just accidentally created the wrong stype
Thanks for your help.
