### ISSUE TITLE
Dark theme bug

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1626]
**Describe the bug**
Just updated to latest 4.8 and have issues with dark theme.
It looks like this:
![image](https://user-images.githubusercontent.com/13370598/115997858-65e0de00-a5ed-11eb-86d2-c30deb415c0c.png)

**To Reproduce**
1. Go to themes
2. Select dark theme
3. See error

**Expected behavior**
Old dark theme look

**Comment by diegocortassa** [comment]
That's a palette definition in src/pyasm/web/palette.py
Try to change line 29 from:
'background':   '#0D1117',
to:
'background':   '#444444',

**Comment by diegocortassa** [comment]
The change was made by @remkonoteboom  Dec 23, 2020 in commit #865ce2934 I reverted it in my installation but never did a PR because i thought there was a reason.

**Comment by listyque** [comment]
Ok. This change helps to fix the issue.
What was the reason to make this?

**Comment by remkonoteboom** [comment]
Not really.  I remember trying out some theming stuff (just before the holidays) and it went in.  I don't use the dark theme all that much so hadn't really noticed.  

You can revert in a pull request.  

All of these colors are overridable per project using project settings:

key:
palette/colors

value:
{
    "background": "#0D1117",
}

**Comment by listyque** [comment]
I think this can be closed.
