### ISSUE TITLE
'FrameRangeWdg' object has no attribute 'create_required_columns'

### ISSUE THREAD

**Issue by aixzhou0216** [Southpaw-TACTIC/TACTIC#1629]
When I create a frame range widget using class pyasm.prod.web.FrameRangeWdg,I got an error
'FrameRangeWdg' object has no attribute 'create_required_columns'
I just do this follow vfx template setup.
Anyone can help me to solve this?
![image](https://user-images.githubusercontent.com/82997546/116528612-a0f55100-a90e-11eb-80b8-cdaeb86b767c.png)

Exception log
`  File "/opt/tactic/tactic/src/pyasm/command/command.py", line 267, in execute_cmd
    ret_val = cmd.execute()`
  `File "/opt/tactic/tactic/src/pyasm/prod/service/api_xmlrpc.py", line 281, in execute
    self2.results = exec_meth(self, ticket, meth, args)`
 ` File "/opt/tactic/tactic/src/pyasm/prod/service/api_xmlrpc.py", line 311, in exec_meth
    results = meth(self, ticket, *new_args)`
 ` File "/opt/tactic/tactic/src/pyasm/prod/service/api_xmlrpc.py", line 5829, in execute_cmd
    Command.execute_cmd(cmd)`
 ` File "/opt/tactic/tactic/src/pyasm/command/command.py", line 267, in execute_cmd
    ret_val = cmd.execute()`
 ` File "/opt/tactic/tactic/src/tactic/ui/manager/element_definition_wdg.py", line 3106, in execute
    self.save(self.search_type, view, self.element_name, widget_key, display_class)`
 ` File "/opt/tactic/tactic/src/tactic/ui/manager/element_definition_wdg.py", line 3240, in save
    self.save_to_view(search_type, view, element_name, element_xml)`
  `File "/opt/tactic/tactic/src/tactic/ui/manager/element_definition_wdg.py", line 3325, in save_to_view
    widget.create_required_columns(full_st)`

Thanks

**Comment by aixzhou0216** [comment]
Problem solved.
The problem is there lost frame_in,frame_out necessary definition.Before use FrameRangeWdg class,they must have been created。

**Comment by diegocortassa** [comment]
@remkonoteboom the create_required_columns() and get_required_columns() is used for some widgets but is not implemented in FrameRangeWdg.

Also create_required_columns() definition exists in tactic.ui.common.BaseTableElementWdg bus is not defined in pyasm.widget.BaseTableElementWdg from which FrameRangeWdg inherits.

Not sure if one of the "BaseTableElementWdg" is deprecated or if create_required_columns() is deprecated.

Do you want me to add a create_required_columns() to FrameRangeWdg() to solve this problem?
