### ISSUE TITLE
Notes in HiddenRow widget isn't working

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1634]
**Describe the bug**
When i try to add a note inside expandable widget button submit note does nothing

**To Reproduce**
1. Open any hidden row table
2. click to add note
3. Write note and click submit
4. See nothing happens

**Expected behavior**
Properly working notes in hidden row widget

**Comment by listyque** [comment]
This is crazy, i can't even figure out how to debug this %)

**Comment by listyque** [comment]
![0DcXKc8c0s](https://user-images.githubusercontent.com/13370598/119509983-cc3a5700-bd79-11eb-8e11-2085d7c841a9.gif)

**Comment by remkonoteboom** [comment]
I will take a look at it this week.

**Comment by listyque** [comment]
Thank you!
