### ISSUE TITLE
How can I get assigned from tactic.ui.table.TaskElementWdg class

### ISSUE THREAD

**Issue by aixzhou0216** [Southpaw-TACTIC/TACTIC#1640]
I want to get task status, assigned from advanced filter.But I didn't find the option
![image](https://user-images.githubusercontent.com/82997546/120963943-0e5d9280-c795-11eb-9d9a-d10b6b270f0d.png)
Is there a way to get the result from tactic.ui.table.TaskElementWdg class?

**Comment by listyque** [comment]
Way to get what?
You want to search sObjects by their tasks statuses? If so, use expression search.
Example of the expression which find all assets with any tasks with status "Assigned": @SOBJECT(vfx/asset.sthpw/task['status', 'Assigned']).
Or particular process with status: @SOBJECT(vfx/asset.sthpw/task['process', 'model']['status', 'Assigned'])

It is better to ask this questions after reading all available docs, and read forums http://forum.southpawtech.com

Git issues is about errors, bugs and feature requests

**Comment by aixzhou0216** [comment]
Thanks for your reply , I will read forums and docs again.
best regard.
