### ISSUE TITLE
"play rv" button doesn't work

### ISSUE THREAD

**Issue by diegocortassa** [Southpaw-TACTIC/TACTIC#1646]
**Describe the bug**
When using VFX, the "play rv" button doesn't work see forums http://forum.southpawtech.com/showthread.php?tid=218

**To Reproduce**
1. Open a project using the VFX plugins
2. Open shots
3. Expand history
4. Click on "play rv"

**Expected behavior**
A player should open showing the clicked video

The logic connected to the button uses the obsolete Applet  to open a local player and does no longer work

**Comment by diegocortassa** [comment]
PR #1647 should solve this issue

**Comment by remkonoteboom** [comment]
I merged the pull request (a while ago).  Is this resolved?

**Comment by diegocortassa** [comment]
Yes! Thank you
