### ISSUE TITLE
Formatted Date Value can not be edited

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1658]
**Describe the bug**
Trying to edit Bid dates of Timestamps with the table edit isn't working

**To Reproduce**
1. Go to any timestamp or bid or any date formatted table value
2. Click on date widget
3. Chose desired date
4. See nothing saves at all

**Expected behavior**
When we click on td value calendar immediately appear and chosen value saved properly

**Screenshots**
![sfcgr83O1p](https://user-images.githubusercontent.com/13370598/123699688-3a39d880-d868-11eb-8e5b-53a8c2638d60.gif)

**Comment by listyque** [comment]
Can anyone confirm this as a bug, and possible way to fix this?
It's blocking pipeline pretty much

**Comment by remkonoteboom** [comment]
I tried a few times to improve how this work, but the date picker is has its own mind.  I can't understand why in this day that date pickers in browsers are so poorly implemented.  I will have to look deeper.  The reason we moved away from the non-native one is that is also had tonnes of problems.

The problem you have here is that the date is not "taken".  You have to press enter.  This admittedly makes this interface have way to many clicks.  1) to edit, 2) to open calendar, 3) select date, 4) enter to take date.  It should be only 2 clicks to select a date.

**Comment by listyque** [comment]
The problem is: Changing the date not making table think it's changed.
Pressing "Enter" doesn't do anything.
Sometimes date it the cell just disappears.
However this date picker works fine when edit with the form edit.

**Comment by remkonoteboom** [comment]
This works for me (in this order): click cell, open date picker, select date, press enter.

Selecting date and clicking off does what you describe.

This is not a good workflow.  I don't like it because it has too many clicks and is too error prone, but I couldn't find a quick fix except making the above work.  I just wanted to tell you what worked for me until we have a better solution.

**Comment by listyque** [comment]
I am afraid it's not working for me. As I said "Enter" does not do anything.
Might be my browser issue, or because I am doing it inside HiddenRow widget...

**Comment by listyque** [comment]
There is a good date picker in material theme for bootstrap. Can we use it?

**Comment by remkonoteboom** [comment]
The reason we moved away from a "custom" date picker is because the all reside inside the DOM and thus are subject to DOM rules.  These means that you have to be careful or the date picker will either be hidden under a div border or cause scroll bars to appear.  The native date picker does not do that.  It is even displayed outside the browser window if necessary.

I didn't try the hidden row.  I can at least check to see if we can make that work.

**Comment by remkonoteboom** [comment]
We can take a look at better date pickers.  I am hoping there is one that is created purely in javascript and is drawn outside of the dom.  This would make it independent of the parent properties of the dom elements.

In the meantime, I have improved the functionality of the inline date edit.  It is still a bit annoying, but hopefully works better.  
Hidden rows should also work now.

**Comment by remkonoteboom** [comment]
The fixes are in the attached pull request.  This pull request also has all of the new table changes.

**Comment by listyque** [comment]
Checked the last commits:
It's working now, but requires double click to show calendar widget. After first click its become editable by keayboard.
About new table, all layouts are broken now:
![image](https://user-images.githubusercontent.com/13370598/127781867-5571bead-9074-4269-8d1a-f0f048043437.png)
![image](https://user-images.githubusercontent.com/13370598/127781869-3228c083-4637-4ea0-a027-db6d423ef493.png)

**Comment by remkonoteboom** [comment]
I think this is due to the grouping.  I haven't explicitly looked at grouping yet.  I think most of the other column are working without grouping.

**Comment by remkonoteboom** [comment]
As for the double click, I haven't found a way to open up the calendar in JavaScript.  Even input.click() and input.show() don't seem to work.

**Comment by listyque** [comment]
Does this fix can will work for classic tables? (for my prod server)

**Comment by remkonoteboom** [comment]
Yes.  It should.  I should have isolated it.
