### ISSUE TITLE
async_get_widget: TypeError: Cannot read property 'getStyle' of undefined

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1677]
**Describe the bug**
On the last update apearring when opening table

**To Reproduce**
1. Open new table
2. See this warning

Is is not appearing all times, and not leave any stacktraces

![image](https://user-images.githubusercontent.com/13370598/128711956-b11eb792-d8e9-4cf5-8bdc-b116499b334f.png)

**Comment by remkonoteboom** [comment]
I seem to be able to get this error if I load some pretty big page (my example was the snapshot table)  and then start switching tabs while it is still loading.  It is giving the same popup.  I this what you are seeing?

**Comment by listyque** [comment]
Yes. Our table are pretty big. With small tables this warning appear not that often.

**Comment by remkonoteboom** [comment]
This has been fixed in the pull request.
