### ISSUE TITLE
TaskElementWdg saving multiple rows not working

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1680]
**Describe the bug**
When you try to save multiple changes in the TaskElementWdg some of the rows will not be saved.

**To Reproduce**
1. Open table with TaskElementWdg
2. Change multiple rows at a time (select two or more statuses and change assignee)
3. Click save
4. See no all changes have been saved

**Expected behavior**
Every changes saves properly

**Comment by remkonoteboom** [comment]
This should be fixed in the attached pull request.
