### ISSUE TITLE
Notes missing their attachments

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1684]
**Describe the bug**
Netes widget showing notes but without attached files

Files actually being added to the repo and db

**To Reproduce**
1. Add note with the note widget
2. Attach file to that note
3. Open this note to see attachment
4. See there is no attachments

**Expected behavior**
All attached files showed properly

Files actually added:
![image](https://user-images.githubusercontent.com/13370598/129478557-d1d15c13-4cef-4eb2-b7bc-40767dcebee9.png)

How it looks in tactic:
![image](https://user-images.githubusercontent.com/13370598/129478565-4c4b4357-9887-4e39-a6f0-3343d7dfbe85.png)

**Comment by remkonoteboom** [comment]
The associated pull request should fix this.
